project_root: ..
results_dir: /root/UMANG/SRR/clinical/results
profile: clinician
platform: illumina
threads: 8
krona:
  taxonomy_dir: .cache/krona_taxonomy
qc:
  illumina_min_quality: 20
  illumina_min_length: 50
  illumina_cut_window_size: 4
  illumina_cut_mean_quality: 20
  nanopore_min_quality: 10
  nanopore_min_length: 500
  nanopore_max_length: 50000
  nanopore_headcrop: 50
  nanopore_tailcrop: 50
host_removal:
  minimap2_preset: map-ont
  bowtie2_sensitivity: very-sensitive
taxonomy:
  kraken2_confidence: 0.0
  centrifuge_min_hitlen_illumina: 22
  centrifuge_min_hitlen_nanopore: 16
  tb_threshold_percent: 1.0
  bracken_level: S
assembly:
  megahit_min_contig_len: 500
  megahit_k_min: 21
  megahit_k_max: 141
  megahit_k_step: 12
  flye_min_overlap: 1000
coverage:
  min_coverage_threshold: 10
amr:
  abricate_min_identity: 80
  abricate_min_coverage: 60
binning:
  metabat2_min_contig: 1500
  metabat2_min_cv: 1.0
  metabat2_min_cv_sum: 1.0
  metabat2_max_p: 95
  metabat2_min_s: 60
